namespace eval sys {
	
	## sys::exec
    ## executes a command
    #
    #  @cmd - command to execute
    ##
    argp::registerArgs run {
	   { cmd   string  ""   {}  }
    }

}

##
# 
##
proc sys::run { args } {
    argp::parseArgs processargs
    set result [catch {eval "exec -ignorestderr -keepnewline $processargs(cmd)"} msg]
    if {[string length $msg] > 0} {
        puts $msg
        return $result
    } else {
        puts $result
    }
}